name: Build documentation

on:
  push:
    branches: [master]

jobs:
  # Build and deploy documentation site
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source form GitHub
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install
      - name: Deploy
        run: |
          poetry run mkdocs gh-deploy --force
