name: Build documentation

on:
  push:
    branches: [master]

# Environment
env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.1.13

jobs:
  # Build and deploy documentation site
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source form GitHub
        uses: actions/checkout@v2

      - name: Install Python runtime and dependencies
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Deploy
        run: |
          poetry run mkdocs gh-deploy --force
